# Generated by Django 4.1.5 on 2023-03-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nippo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('study_content', models.CharField(max_length=100)),
                ('meeting_check', models.CharField(max_length=100)),
                ('lessen_check', models.CharField(max_length=100)),
                ('impressions', models.CharField(max_length=300, null=True)),
                ('report_direction', models.CharField(max_length=40, null=True)),
                ('select_date', models.DateTimeField(null=True)),
                ('ai_check', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nippo',
            },
        ),
    ]
